### ISSUE TITLE
Application Structure

### ISSUE THREAD

**Issue by loljoho** [loljoho/ainu#17]
## Overview

Refactor current codebase to reflect proposed application structure

## Task List

 - [ ] Refactor configuration and environmental variables
   - [ ] Load secrets and keys from `.env`
   - [ ] Separate application configuration file and schema
 - [ ] Refactor directory structure
   - [ ] Create `src/lib/` for utilities, common, etc.
 - [ ] Implement modular structure for bot commands and behaviors
   - [ ] Create Weather module
   - [ ] Create Forecast module
   - [ ] Create Debug module
   - [ ] Create Points module

## Details

```
├── dist/                       --> Build Directory
│
├── src/                        --> Source Directory
│   │
│   ├── data/                   --> Data files
│   ├── config/                 --> Application Configuration
│   │   │
│   │   ├── database.ts
│   │   ├── config.ts
│   │   │
│   │   ├── config.json         --> Bot Configuration
│   │   └── config.example.json
│   │
│   ├── lib/                    --> Core Bot Code
│   │   ├──
│   │   └──
│   │
│   ├── utils/                  --> Utility Scripts
│   │   ├──
│   │   └──
│   │
│   ├── modules/                --> Command/Behavior Code
│   │   ├── Weather/
│   │   │   ├── Weather.ts
│   │   │   └── Forecast.ts
│   │   └── index.ts
│   │
│   ├── bot.ts
│   └── index.ts
├── .env                        --> Environmental Variables
└── package.json                --> Manifest File
```

**Comment by loljoho** [comment]
## Proposed Structure


```
├── src/                        --> Source Directory
│   ├── core/                   --> Core Bot Code
│   ├── modules/                --> Modules for Bot Commands
│   ├── utils/                  --> Utility Functions & Helpers
│   │
│   ├── config/                 --> Application Configuration Files
│   ├── data/                   --> Necessary JSON Data Files
│   │
│   ├── bot.ts
│   └── index.ts
```
